### ISSUE TITLE
Would you please update the defense MID, thanks.

### ISSUE THREAD

**Issue by mitthumeng** [FLAIR-THU/VFLAIR#12]

**Comment by LindaLydia** [comment]
Since MID defends against attacks by adding additional bottleneck (or you can say, additional model layers in the implementation), it is not included as a defense function. Instead, MID is added to the VFL framework during model preparation stage. 
You can find the already included implemented in `src/load/LoadModels.py`, in function `load_defense_models`.

**Comment by LindaLydia** [comment]
Since the code does not need any update as MID is already included, I will close this issue.

**Comment by mitthumeng** [comment]
Thanks a lot!
