### ISSUE TITLE
Can not find the setting of splitVFL.

### ISSUE THREAD

**Issue by Whitepinkwolf** [FLAIR-THU/VFLAIR#13]
I can only find the settings for aggVFL in the main_task folder, but not splitVFL. Could you please provide more guidance on splitVFL?

**Comment by LindaLydia** [comment]
As a trainable global model is used in splitVFL instead of a non-trainable global function, you can simply modify the config json file for aggVFL as the following to construct a splitVFL setting. 
```
{
    ....
    "model_list":{
        ....
        "apply_trainable_layer": 1,
        "global_model": "ClassificationModelHostTrainableHead"
    }
}
```
You can further change the "global_model" to other trainable models that meets your need.

We have also added several example configureation files of splitVFL under folder `./src/configs/main_task/2_party/splitVFL/`. Please check our latest commit `a9594d8badf7d250d77c5746e5a1de01b336fd47` on branch `main` for finding them.
